-- MySQL Script generated by MySQL Workbench
-- seg 22 jun 2026 10:20:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_recomendacoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_recomendacoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_recomendacoes` ;
USE `banco_recomendacoes` ;

-- -----------------------------------------------------
-- Table `banco_recomendacoes`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_recomendacoes`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_recomendacoes`.`recomendacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_recomendacoes`.`recomendacao` (
  `id_recomendacao` INT NOT NULL AUTO_INCREMENT,
  `id_categoria` INT NOT NULL,
  `titulo` VARCHAR(80) NOT NULL,
  `descricao` TEXT NOT NULL,
  `nota` TINYINT NOT NULL,
  `data_cadastro` DATE NOT NULL,
  `recomendado` TINYINT NOT NULL,
  PRIMARY KEY (`id_recomendacao`, `id_categoria`),
  INDEX `fk_recomendacao_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_recomendacao_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `banco_recomendacoes`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
